// When loading the site, randomly select a Text to be displayed inside the srolling header.
const headerText = [
    "BREAKING NEWS: uhhhhhhhhuhhyhhuuhhyyh...... hi.",
    "I have way too much caffeine in my blood atm oh god",
    "Me likey Earthbound i'm literally a Mr. Saturn =333",
    "Hmmm... There really isn't any news to speak of today...",
    "Snake, what happened? Snake? SNAAAAAAAAAAKE?!",
    "I'm Ness.... It's been a long road getting here... Soon, i'll be... Soon, i'll be... Soon, i'll be... What will happen to us? W...what's happening? My thoughts are being written out on the wall... or are they?",
    "Garfield, you fat cat. You are so big and fat. Why are you so fat?",
    "\" ♪ Na na na na na na na na na na Katamari Damacy! ~ ♪ \"",
    "Inspect element me. I DARE you!", // HIIIIIIIIIII :333333 !!!!1!1 Feel free to look at my code but just a heads up: MY CODE SUCKS.
    "Gooby Gibber Flibber Womb, Smeckle Tickle Zippy Zap, Gowanga Bowanga Fawiggle Womb.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi nec pulvinar tortor. Sed cursus, magna et suscipit porta, neque massa hendrerit felis, hendrerit varius tellus lorem in lorem. Donec feugiat, erat eget malesuada euismod, purus odio varius tellus, ut pretium justo arcu eget ante. Integer fringilla gravida urna ut porta. Proin fringilla interdum ex, in varius nibh sollicitudin ac. Pellentesque consectetur nunc id vulputate congue. Donec erat enim, pellentesque sed ex non, auctor vulputate mauris. Fusce ac ante nec lacus tempor vehicula vel ultrices mi. Vivamus lacus neque, convallis a hendrerit molestie, luctus eget tortor. Nullam eu vestibulum lorem. Suspendisse euismod ligula ex.",
    "Why did Nobuo Uematsu go so hard on Dancing Mad i mean HOLY COW",
    "Sharon, please come back with the kids",
    "MEOW! MEOW! MEOW! MEOW! MEOW! MIAU! MEOW! MEOW! MEOW! MEOW! NYA! MEOW! MEOW! MEOW? MEOW! MEOW! meow. MEOW!",
    "Mori, who or what is an Azure ?",
    "melon.", // FACADE REFERENCE WOOOOOO
    "McDonalds and you~ McDonalds and you~ Fresh scrambled eggs, Sausage, Hotcakes~ Juice and Coffee too~ JUST LIKE SUNSHINE EVERY MOOOORNING~ MCDOOOONALDS AND YOUUUUUUUU~",
    "\" ♪ So take me baaack in tiiiiiiiiimmme~ ♪ To another world~ ♪ When you caaaan beeee miiiiiiiiiine~ ♪ We don't have to worry~ ♪ When you're byyyyy myyy siiiiiiiiide~ ♪ Theres nothing i don't know~ ♪ Theres nothing tooooo deeeciiiiiiiide~ ♪ Apart from where we want to gooooooo~ ♪\"",
    "I have no idea what to draw aaaaaaaaaaaaa =[",
    "I know! I gotta believe!",
    "Fuck you, Baltimore!",
    "Roll up~ ! ♪ Roll up for the Mystery Tour! ♪",
    "All right, so here we are, in front of the elphants. The cool thing about these guys is that they have really, really, really long... uhm... trunks. And thats cool. And that's pretty much all there is to say.",
    "Once, there was an ugly barnacle. He was so ugly, that everyone died. The end!",
    "Why do they call it Oven, when you of in the cold food of out hot eat the food",
    "RAM RANCH REALLY ROCKS!",
    "What would Brian Boitano do, if he was here today? I'm sure he'd kick an ass or two! That's what Brian Boitano do!",
    "\"♪ Da Coconut Nut is a giant nut, if you eat too much, you'll get very fat. (very fat ~) Now, da Coconut Nut is a big, big nut, but this delicious nut is not a nut ! It's a coco fruit. (it's a coco fruit ~) Of the coco tree. (of the coco tree ~) From the coco palm family ! ♪\"",
    "\"♪ Super Mario RPG ♪ Sonic the Hedgehog, Donkey Kong 3 ♪ Adventures of Lolo 1 and 2 ♪ King's Knight, Dig Dug, Chew Man Fu ♪ Harvest Moooooon~ ♪ League Puzzle Pokemoooon~ ♪ ToeJam & Earl in Panic on Funkotroooon~ ♪ Castlevania, Fatal Fury, Ninja JaJaMaru-kun ♪ ActRaiser, Blazing Lazers, Bases Loaded, Mega Turrican ♪ Cybernator, Rolling Thunder, Dynastic Hero ♪ Bubble Bobble, Double Dribble, Double Dragon, F-Zero ♪ F-Zero X ~ ♪ and Donkey Kong Jr. Maaaath ~ ! ♪ Ninja Gaiden 1 ♪ Ninja Gaiden 2 ♪ Ninja Gaiden 3 ♪ Crusin' USA ♪\"",
    "\"♪ Super Mario - oohh R-P-G! ♪ It is the only one just for me ♪ When i play the game, i get lost in a phase ♪ Then i find out I'm stuck in Geno's Maze ♪ There are many secrets in this game ♪ Many of which drive some peeps insane ♪ Why we try to cheat in a really good game? ♪ Just sounds like crap and it makes you look lame! ♪ Exiting the forest is super simple! ♪ All you do is follow these path tuuuurns~ ♪ For the reeessstt of yoouur gaming liiife~ ♪\"",
    "\"♪ I wanna flyyy skyyy hiiiigh~ ♪ Let's goooo together~ ♪ We are going this waaayyy~ ♪ At maximum speed on a wiiing~ ♪ We're flying ♪    ♪ ♪ ♪    ♪ I wanna flyyy skyy hiiiigh~ ♪ Let's goooo together~ ♪ You can even see the horizooon~ ♪ We driiiift together~ ♪ Forever ♪ Oooover the bridge~ ♪ Cut through the traffic ♪ Flyyyying hiiigh~ Feeeeliing goood~ ♪ Blue, blue skiiesss ♪ Blue, blue skiiesss I see~ ♪ Blue, blue skiiesss ♪ Blue, blue skiiesss I see~ ♪\"",
    "\"♪ ROOOLLING STAAAAAAART! ♪ ROOOLLING STAAAAAAART! ♪\"",
    "\"♪ DAYTONAAAAAAA~ ♪ DAYTONAAAAAAA~ ♪ LET'S GO AWAY ♪ DAYTONAAAAAAA~ ♪\"",
    "\"It is gud day to be not dead !\"",
    "KRUSTY KRAAAYEAAEEEYEAAAEYEAAAABB PIZZA IS THE PIZZA YEEAAEEAAA FOR YOU AND...      MEEEEEEEEEEEHEEEEEEEEEEHEEEEEHEEEEEE!!",
    "i main ness btw.",
    "i main taokaka btw.",
    "i main heavy and medic btw.",
    "\"♪ Fly me to the moon and let me play among the stars~ ♪ Let me see what spring is like on jupiter and mars~ ♪ In other words, ~    Hold my hand~ ♪ In other words, ~    Darling, kiss me~ ♪  Fill my heart with song and let me sing forevermore~ ♪ You are all i long for~    All i worship and adore~ ♪ In other words, ~    Please be true~ ♪ In other words, ~    I love you~ ♥    ♪\"",
    "\"♪ I~ ♪ I will be king~ ♪ and you~ ♪ You will be Queen~ ♪ Though nothing~ ♪ will drive them away~ ♪ We can beat them, ~ ♪ just for one day~ ♪ Oh we can be Heroes, ~ ♪ just for one day~ ♪\"",
    "\" ♪ Ashes to Ashes~ ♪ Funk to funky~ ♪ We know Major Tom's a junkie~ ♪ Strung out in heaven's high~ ♪ Hitting an all-time low~ ♪ \"",
    "\" ♪ For here~ ♪ Am i sitting in a tin can~ ♪ Far~ above the world~ ♪ Planet earth is blue and there's nothing i can do~ ♪ \"",
    "Fetch me a fire extinguisher. A good one. With the foam.",
    "\"♪ Give it all you've got~ ♪ Can't stop now, keep moving~ ♪ Give it all you've got~ ♪    ♪ ♪ ♪    ♪ Give it all you've got~ ♪ Dance, dance, dance, get on it~ ♪ Take it to the top~ ♪ \"",
    "Get crazy with the Cheese Whiz !",
    "\" ♪ Reese's Puffs, Reese's Puffs, ♪ Peanut butter chocolate flavour~ ♪ Reese's Puffs, Reese's Puffs, ♪ In the A.M. it's the flavour i savour~ ♪ Peanut butter and chocolate too~ ♪ You know how i do, that's what i wake up to~ ♪ My Reese's Puffs inspired this rhyme~ ♪ That peanut butter and chocolate combination's on time~ ♪ Reese's Puffs, Reese's Puffs (Eat em up, Eat em up) ♪ Reese's Puffs, Reese's Puffs (Eat em up, Eat em up) ♪ Reese's Puffs, Reese's Puffs (Eat em up, Eat em up) ♪ Reese's Puffs, Reese's Puffs (Eat em up, Eat em up) ♪ \"",
    "\" ♪ And if the dam breaks open many years too soon~ ♪ And if there is no room upon the hill~ ♪ And if your head explodes with dark forebodings too~ ♪ I'll see you on the dark side of the moon~ ♪ \"",
    "\" ♪ All that you touch~ ♪ And all that you see~ ♪ All that you taste~ ♪ All you feel~ ♪ And all that you loved~ ♪ And all that you hate~ ♪ All you distrust~ ♪ All you save~ ♪ And all that you give~ ♪ And all that you deal~ ♪ And all that you buy, beg, borrow or steal~ ♪ And all you create~ ♪ And all you destroy~ ♪ And all that you do~ ♪ And all that you say~ ♪ And all that you eat~ ♪ And everyone you meet~ ♪ And all that you slight~ ♪ And everyone you fight~ ♪ And all that is now~ ♪ And all that is gone~ ♪ And all that's to come~ ♪ And everything under the sun is in tune~ ♪ But the sun is eclipsed by the moon~ ♪ \"",
    "\" ♪ There is no pain, you are receding~ ♪ A distant ship, smoke on the horizon~ ♪ You are only coming through in waves~ ♪ Your lips move, but i can't hear what you say~ ♪ When i was a child, i had a fever~ ♪ My hands felt just like two baloons~ ♪ Now i've got that feeling once again~ ♪ I can't explain, you would not understand~ ♪ This is not how i am~ ♪ I~ have become comfortably numb~ ♪ \"",
    "\" ♪ We don't need no education~ ♪ We don't need no thought control~ ♪ No dark sarcasm in the classroom~ ♪ Teacher, leave them kids alone~ ♪ Hey, teacher, leave them kids alone! ♪ All in all it's just another brick in the wall~ ♪ All in all you're just another brick in the wall~ ♪ \"",
    "\" ♪ So you~ Thought you~ Might like to~ Go to the Show~ ♪ To feel the warm thrill of confusion, that space-cadet glow~ ♪ Tell me, is something eluding you, Sunshine?~ ♪ Is this not what you expected to see?~ ♪ If you wanna find out what's behind these cold eyes, you'll just have to claw your way through this disguise!~ ♪♪♪ LIGHTS! ♪ ROLL THE SOUNDEFFECTS! ♪ ACTION! ♪ DROP IT! DROP IT ON THEM! ♪ \"",
    "\" ♪ Let's do the time warp again~ ♪ Let's do the time warp again~ ♪ It's just a jump to the left~ ♪ And then a step to the riiiiiight~ ♪ You put your hands on your hips~ ♪ You bring your knees in tiiiiight~ ♪ But it's the pelvic thruuuust~ ♪ That really drives you insaaaaane~ ♪ Let's do the time warp again~ ♪ Let's do the time warp again~ ♪ \"",
    "musicless dancing in the street is peak comedy. thank you for listening to my ted talk. good night.",
    "\" there's no dark side of the moon, really. matter of fact, it's all dark. \"",
    "it's a unix system... i know this...",
    "Remember, kids ! Don't copy that floppy !",
    "i can't be the only one who misses the comedic mario sports intros from the gamecube and wii era, especially the ones with wario and waluigi trying to ruin the fun for everyone. i mean for crying out loud the mario power tennis intro could have aired standalone on tv as a mario short or something like that ! they were that good ! no joke !",
    "You know what they say: All toasters toast toast !",
    "\" ♪ Matte na yo~ Pichi-Hime~ ♪ Tasuke ni~ ♪ Umi koe yama koe~ ♪ Tani koe oka koete~ ♪ Bokura Super! ♪ Dakedo I don't know~ ♪ Bokura Super! ♪ Dakedo what to do~ ♪ With my love~ ♪ \"",
    "Sometimes i wish i could be a cat... No job, no bills to pay, absolutely no responsibilities... It would be me just laying next to a window all day and letting the sun shine on to my big, round belly ! And as a cat you could behave like an absolute dickhead and humans would still go \" Awwww =3 \" and call you cute ! It would be perfect !",
    "Node Graph out of Date. Rebuilding...",
    "I don't think, therefore i am not",
    "I AM ERROR",
    "MY LEG!",
    "aaaAAAahhhh~ the fffrench~... champange~...",
    "never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other way- never could be any other w-",
    "Fun, fun, fun, fun, fun, fun, fun, fun, fun, fun, fun, fun, fun.",
    "Road Work Ahead? Uhh. Yeah. I sure hope it does...",
    "\" I'm feeling a little light headed. Maybe you should drive. \"",
    "\" ♪ There was something in the air that night~ ♪ The stars were bright, Fernando~ ♪ They were shining there for you and me~ ♪ For liberty, Fernando~ ♪ Though we never thought that we could lose, theres no regret~ ♪ If i had to do the same again~ ♪ I would, my friend, Fernando~ ♪ If i had to do the same again~ ♪ I would, my friend, Fernando~ ♪ \"",
    "\" ♪ We'll meet again~ ♪ Don't know where~ ♪ Don't know when~ ♪ But i know we'll meet again some sunny day~ ♪ Keep smiling through~ ♪ Just like you~ ♪ always do~ ♪ 'Til the blue skies drive the dark clouds far away~ ♪ \"",
    "\" ♪ Like the wind~ ♪ You came here running~ ♪ Take the consequence of living~ ♪ There's no space~ ♪ There's no tomorrow~ ♪ All we need is some communication~ ♪ Check it in, check it out, but the sun will never shine~ ♪ Paranoid anyway, in the subways of your mind~ ♪ \"",
    "\" ♪ This is the end~ ♪ Beautiful friend~ ♪ This is the end~ ♪ My only friend, the end~ ♪ Of our elaborate plans, the end~ ♪ Of everything that stands, the end~ ♪ No safety or surprise, the end~ ♪ I'll never look into your eyes again~ ♪ \"",
    "\" I've got a hole in me pocket ! \""
    "\" It's all in the mind, y'know \""
];

const indexID = Math.floor(Math.random() * headerText.length);
document.getElementById('marqueeText').innerText = headerText[indexID];
